# language type:
language:
- cpp
- Objective-c

# compilator system:
compiler:
- clang
- gcc

# build branch requested
branches:
  only:
    - master
    - dev

# previous actions:
before_script: 
  - git clone --depth 0 https://github.com/HeeroYui/etk.git
  - git clone --depth 0 https://github.com/HeeroYui/build.git
  - git clone --depth 0 https://github.com/HeeroYui/gtest.git

#install Gcc to have lisstdc++ 4.8 & gcc 4.8
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo rm /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++

# build sequence with Lutin :
script: 
  - if [ "$CXX" == "clang++" ]; then ./build/lutin.py -C -P -cclang -mdebug -p ejson_test; fi
  - if [ "$CXX" == "g++" ]; then ./build/lutin.py -C -P -cgcc -mdebug -p ejson_test; fi

after_script:
  - if [ "$CXX" == "clang++" ]; then ./out/Linux_x86_64/debug/staging/clang/ejson_test/usr/bin/ejson_test; fi
  - if [ "$CXX" == "g++" ]; then ./out/Linux_x86_64/debug/staging/gcc/ejson_test/usr/bin/ejson_test; fi

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com
